title: ./peepingtomfoolery
author: graham j bailey
email: pumpabooks@gmail.com

# Build settings
theme: minima
# generate social links in footer
social_links:
twitter: jekyllrb
github:  jekyll
rss: rss

